// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace HealthMonitorSystem {
	
	
	public partial class ChangePassword {
		
		protected System.Web.UI.WebControls.Button btnSubmit;
		
		protected System.Web.UI.WebControls.Label lblError;
		
		protected System.Web.UI.WebControls.Button btnCancel;
		
		protected System.Web.UI.WebControls.TextBox txtRetypePassword;
		
		protected System.Web.UI.WebControls.Content login;
		
		protected System.Web.UI.WebControls.TextBox txtPassword;
	}
}
