// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace HealthMonitorSystem {
	
	
	public partial class _Default {
		
		protected System.Web.UI.WebControls.Button btnCancel;
		
		protected System.Web.UI.WebControls.TextBox txtpassword;
		
		protected System.Web.UI.WebControls.Content login;
		
		protected System.Web.UI.WebControls.Button btnlogin;
		
		protected System.Web.UI.WebControls.LinkButton lnkRegister;
		
		protected System.Web.UI.WebControls.LinkButton lnkforgotpwd;
		
		protected System.Web.UI.WebControls.TextBox txtuser;
	}
}
