// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace HealthMonitorSystem {
	
	
	public partial class DoctorsPage {
		
		protected System.Web.UI.WebControls.Button btnCancel;
		
		protected System.Web.UI.WebControls.Content doctors;
		
		protected System.Web.UI.WebControls.LinkButton btnView;
		
		protected System.Web.UI.WebControls.TextBox txtRemarks;
		
		protected System.Web.UI.WebControls.PlaceHolder phRemarks;
		
		protected System.Web.UI.WebControls.LinkButton btnRemarks;
		
		protected System.Web.UI.WebControls.GridView gv;
	}
}
