// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace HealthMonitorSystem {
	
	
	public partial class DoctorPatient {
		
		protected System.Web.UI.WebControls.Button btnAssociate;
		
		protected System.Web.UI.WebControls.Content hist;
		
		protected System.Web.UI.WebControls.LinkButton lnkBack;
		
		protected System.Web.UI.WebControls.Button btnClear;
		
		protected System.Web.UI.WebControls.GridView gvHist;
		
		protected System.Web.UI.WebControls.CheckBox chkSelect;
		
		protected System.Web.UI.WebControls.DropDownList ddlDoctor;
	}
}
