// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace HealthMonitorSystem {
	
	
	public partial class ForgotPwd {
		
		protected System.Web.UI.WebControls.Button btnSubmit;
		
		protected System.Web.UI.WebControls.TextBox txtDay;
		
		protected System.Web.UI.WebControls.Label lblErrors;
		
		protected System.Web.UI.WebControls.DropDownList listSecQuestion;
		
		protected System.Web.UI.WebControls.TextBox txtYear;
		
		protected System.Web.UI.WebControls.TextBox txtAnswer;
		
		protected System.Web.UI.WebControls.TextBox txtUserId;
		
		protected System.Web.UI.WebControls.DropDownList listMonth;
		
		protected System.Web.UI.WebControls.Button btnReset;
		
		protected System.Web.UI.WebControls.Content login;
	}
}
