// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace HealthMonitorSystem {
	
	
	public partial class PatientEntry {
		
		protected System.Web.UI.WebControls.Button btnHelp;
		
		protected System.Web.UI.WebControls.TextBox txtglucose;
		
		protected System.Web.UI.WebControls.Content login;
		
		protected System.Web.UI.WebControls.TextBox txtpulserate;
		
		protected System.Web.UI.WebControls.TextBox txtbphigh;
		
		protected System.Web.UI.WebControls.Button btnCancel;
		
		protected System.Web.UI.WebControls.DropDownList listpid;
		
		protected System.Web.UI.WebControls.Label lblpatid;
		
		protected System.Web.UI.WebControls.TextBox txtdescription;
		
		protected System.Web.UI.WebControls.DropDownList listpainlevel;
		
		protected System.Web.UI.WebControls.Button btnpatient;
		
		protected System.Web.UI.WebControls.LinkButton lnkBack;
		
		protected System.Web.UI.WebControls.TextBox txttemp;
		
		protected System.Web.UI.WebControls.TextBox txtbplow;
	}
}
