// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System.Web.UI.WebControls;

namespace HealthMonitorSystem {
	
	
	public partial class PatientHist {
		
		protected System.Web.UI.WebControls.Label lblError;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.GridView gvHist;
		protected Label lblName;
	}
}
