// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace HealthMonitorSystem {
	
	
	public partial class Register {
		
		protected System.Web.UI.WebControls.DropDownList listGender;
		
		protected System.Web.UI.WebControls.TextBox txtAnswer;
		
		protected System.Web.UI.WebControls.TextBox txtLastName;
		
		protected System.Web.UI.WebControls.Button btnCancel;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox txtAddress;
		
		protected System.Web.UI.WebControls.DropDownList listSecurityQuestion;
		
		protected System.Web.UI.WebControls.TextBox txtRetypePwd;
		
		protected System.Web.UI.WebControls.TextBox txtFirstName;
		
		protected System.Web.UI.WebControls.TextBox txtPassword;
		
		protected System.Web.UI.WebControls.Button btnRegister;
		
		protected System.Web.UI.WebControls.TextBox txtUserId;
	}
}
