
//-----------------------------------------------------------------------
// Copyright (c) 2009 Rohini Venkataramaiah. 

//This file is part of HealthMonitoringSystem.
//HealthMonitoringSystem is free software: you can redistribute it and/or modify
//it under the terms of the GNU General Public License as published by
//the Free Software Foundation, either version 3 of the License, or
//(at your option) any later version.

//HealthMonitoringSystem is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//GNU General Public License for more details.

//You should have received a copy of the GNU General Public License
//along with HealthMonitoringSystem.  If not, see <http://www.gnu.org/licenses/>.
//-----------------------------------------------------------------------

// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------


namespace HealthMonitorSystem {
	
	
	public partial class Register {
		
		protected System.Web.UI.WebControls.TextBox txtAnswer;
		
		protected System.Web.UI.WebControls.DropDownList listGender;
		
		protected System.Web.UI.WebControls.Content login;
		
		protected System.Web.UI.WebControls.TextBox txtLastName;
		
		protected System.Web.UI.WebControls.Button btnCancel;
		
		protected System.Web.UI.WebControls.DropDownList listMonth;
		
		protected System.Web.UI.WebControls.TextBox txtDay;
		
		protected System.Web.UI.WebControls.Label lblErrors;
		
		protected System.Web.UI.WebControls.TextBox txtYear;
		
		protected System.Web.UI.WebControls.TextBox txtAddress;
		
		protected System.Web.UI.WebControls.DropDownList listSecQuestion;
		
		protected System.Web.UI.WebControls.TextBox txtRetypePwd;
		
		protected System.Web.UI.WebControls.TextBox txtFirstName;
		
		protected System.Web.UI.WebControls.TextBox txtPassword;
		
		protected System.Web.UI.WebControls.Button btnRegister;
		
		protected System.Web.UI.WebControls.TextBox txtUserId;
	}
}
